chunking:
  chunk_size: 400
  overlap: 50
  tokenizer: cl100k_base
  preserve_boundaries: true

embedding:
  model: openai/text-embedding-3-small
  version: v1
  dimensions: 1536
  batch_size: 100
  max_retries: 3
  timeout_seconds: 30.0
  api_key: null

index:
  backend: pinecone
  index_name: labarchives-semantic-search
  namespace: null
  api_key: null
  environment: us-east-1
  url: null

incremental_updates:
  enabled: true
  schedule: "0 2 * * *"
  batch_size: 200
  last_indexed_file: data/.last_indexed
