apiVersion: v1
kind: Secret
metadata:
  name: labarchives-mcp-secrets
  namespace: default
  labels:
    app: labarchives-mcp-server
    version: "0.1.0"
    component: authentication
  annotations:
    description: "Kubernetes Secret for LabArchives MCP Server credentials"
    security.policy: "restricted-access"
    compliance.standards: "SOC2,ISO-27001,HIPAA,GDPR"
type: Opaque
data:
  # LabArchives API Access Key ID - Base64 encoded
  # This is the primary identifier for API authentication
  # Format: Base64 encoded string of the access key ID
  LABARCHIVES_AKID: <Base64-encoded string>
  
  # LabArchives API Access Secret/Token - Base64 encoded
  # This can be either:
  # - Permanent API password for service accounts
  # - Temporary app authentication token for SSO users (1-hour lifetime)
  # Format: Base64 encoded string of the secret/token
  LABARCHIVES_SECRET: <Base64-encoded string>
  
  # LabArchives username (optional) - Base64 encoded
  # Required for SSO/token authentication flow
  # Used to exchange app authentication token for user ID
  # Format: Base64 encoded email address
  LABARCHIVES_USER: <Base64-encoded string, optional>
  
  # LabArchives API base URL (optional) - Base64 encoded
  # Regional API endpoint selection
  # Default: https://api.labarchives.com/api
  # Australia: https://auapi.labarchives.com/api
  # Format: Base64 encoded URL string
  LABARCHIVES_API_BASE: <Base64-encoded string, optional>

---
# RBAC Configuration for Secret Access Control
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: labarchives-mcp-secret-reader
  labels:
    app: labarchives-mcp-server
    security.purpose: "secret-access-control"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["labarchives-mcp-secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labarchives-mcp-secret-binding
  namespace: default
  labels:
    app: labarchives-mcp-server
    security.purpose: "secret-access-control"
subjects:
- kind: ServiceAccount
  name: labarchives-mcp-server
  namespace: default
roleRef:
  kind: Role
  name: labarchives-mcp-secret-reader
  apiGroup: rbac.authorization.k8s.io

---
# ServiceAccount for the MCP Server deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: labarchives-mcp-server
  namespace: default
  labels:
    app: labarchives-mcp-server
    security.purpose: "pod-identity"
  annotations:
    description: "Service account for LabArchives MCP Server pods"
    security.policy: "least-privilege"
automountServiceAccountToken: true