name: Draft JOSS PDF

on:
  workflow_dispatch:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml
  pull_request:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    name: Build draft PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload draft artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper-draft
          path: paper.pdf
